{{- if .Values.cappBuild.onCommit.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "container-app-operator.fullname" . }}-git-webhook-service
  labels:
  {{- include "container-app-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
    {{- include "container-app-operator.selectorLabels" . | nindent 4 }}
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
{{- end }}
