---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.16.2
  name: cappconfigs.rcs.dana.io
spec:
  group: rcs.dana.io
  names:
    kind: CappConfig
    listKind: CappConfigList
    plural: cappconfigs
    singular: cappconfig
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: CappConfig is the Schema for the cappconfigs API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: CappConfigSpec defines the desired state of CappConfig
            properties:
              autoscalerConfig:
                properties:
                  activationScale:
                    type: string
                  concurrency:
                    type: string
                  cpu:
                    type: string
                  memory:
                    type: string
                  rps:
                    type: string
                required:
                - activationScale
                - concurrency
                - cpu
                - memory
                - rps
                type: object
              dnsConfig:
                properties:
                  cname:
                    type: string
                  issuer:
                    type: string
                  provider:
                    type: string
                  zone:
                    type: string
                required:
                - cname
                - issuer
                - provider
                - zone
                type: object
            type: object
          status:
            description: CappConfigStatus defines the observed state of CappConfig
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
