name: tests
on:
  pull_request:
    branches:
      - main
    types: [opened, reopened, synchronize]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'examples/**'
      - 'images/**'
      - 'LICENSE'
      - 'OWNERS'

jobs:
  unit-test:
    name: unit-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6.0.1

    - name: Cache Go tools
      uses: actions/cache@v5
      with:
        path: |
          ./bin
        key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}
        restore-keys: |
          ${{ runner.os }}-tools-

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - name: Run unit-tests
      run: make test

  e2e-tests:
    name: e2e-tests
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      E2E_SKIP_CLEANUP: "true"
      E2E_GINKGO_PROCS: 8
      IMAGE_REGISTRY: kind-registry:5000
      KIND_VERSION: v0.25.0
      K8S_VERSION: v1.30.4
      IMAGE_TAG: test-${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Cache Go tools
        uses: actions/cache@v5
        with:
          path: |
            ./bin
          key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}
          restore-keys: |
            ${{ runner.os }}-tools-

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build container-app image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: |
            container-app-operator:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=min

      - name: Start kind cluster
        uses: container-tools/kind-action@v2
        with:
          cluster_name: hub
          version: ${{env.KIND_VERSION}}
          node_image: kindest/node:${{env.K8S_VERSION}}
          kubectl_version: ${{env.K8S_VERSION}}
          registry: true

      - name: Load image into kind cluster
        run: kind load docker-image container-app-operator:${IMAGE_TAG} --name hub

      - name: Setup prerequisites
        run: make prereq

      - name: Deploy controller to cluster
        run: make install deploy IMG=container-app-operator:${IMAGE_TAG}

      - name: Create CappConfig
        run: make create-cappConfig

      - name: Await controller to be ready
        uses: jupyterhub/action-k8s-await-workloads@v3
        with:
          workloads: ""
          namespace: "container-app-operator-system"
          max-restarts: 0

      - name: Run e2e tests
        run: make test-e2e